# ops/helm/voter-app/values.yaml
# replicaCount: 1

# Imagens (Substitua pelo seu usu√°rio do Docker Hub)
backend:
  image: seu-usuario/voter-api:latest
  port: 8000
  env:
    REDIS_HOST: "redis-service"
    REDIS_PORT: "6379"

frontend:
  image: jonatasilva/votar-frontend:0.0.1
  port: 80
service:
  type: LoadBalancer