apiVersion: apps/v1
kind: Deployment
metadata:
  name: votar-ui
spec:
  replicas: {{ .Values.replicaCount | default 2 }}
  selector:
    matchLabels:
      app: votar-ui
  template:
    metadata:
      labels:
        app: votar-ui
    spec:
      containers:
        - name: votar-ui
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: votar-ui-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.port }}
  selector:
    app: votar-ui